# Generated by Django 4.2.22 on 2025-10-31 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycomm', '0002_product_created_at_alter_users_username_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totalamount',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
