# Generated by Django 4.2.22 on 2025-11-01 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycomm', '0003_orders_totalamount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='usersInfo',
        ),
        migrations.AlterField(
            model_name='orders',
            name='totalamount',
            field=models.IntegerField(null=True),
        ),
    ]
